SubBt/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to create BT Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SubBt/force-app/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>Standard text to tie back to PO&apos;s, Invoices, etc...</inlineHelpText>
    <label>Project #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SubBt/force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Type is defined by Master and Standard.  A Master Project is a Project that you may want to clone at another point in time.  You are not able to clone a Standard Project.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SubBt/force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Schedule #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SubBt/force-app/main/default/objects/Schedule__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SubBt/force-app/main/default/objects/Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

SubBt/force-app/main/default/objects/Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Type is defined by Master and Standard.  A Master Schedule is a Schedule that you may want to clone at another point in time.  You are not able to clone a Standard Schedule.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SubBt/force-app/main/default/classes/BT_ImportScheduleTest.cls
/*
Copyright (c) 2017-2018, BuilderTek.
All rights reserved. 

Developed By: Sagar
Date:  19-Nov-2018
*/
@isTest
public class BT_ImportScheduleTest {
     @testSetup static void setupBaseData() {
        // SetupTestData.setupBaseData();
    }
    
    // public static testMethod void test1() {
    // 	schedule__c sd = new schedule__c();
    // 	sd.Description__c = 'test';
    // 	sd.Type__c = 'Master';
    // 	sd.Project__c = [Select id from project__c LIMIT 1].Id;
    // 	insert sd;
    	
    // 	ApexPages.StandardController sc = new ApexPages.StandardController(sd);
    //     BT_ImportSchedule testa = new BT_ImportSchedule(sc);
    //     testa.masterSchedules[0].isSelected = true;
    //     testa.save();
        
    //     Apexpages.currentPage().getParameters().put('Id', sd.Project__c);
    //     ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(new List<Schedule__c>{sd});
	//     stdSetController.setSelected(new List<Schedule__c>{sd});
	//     BT_ImportSchedule test = new BT_ImportSchedule(stdSetController);
	//     System.assertEquals('Test','Test');
	 
    // }
}